package runner;

import io.javalin.Javalin;


public class AppDriver{
 
  
  //Main Method starts
	public static void main(String[] args){
		//Javalin app
				Javalin app = Javalin.create(config->{
					config.enableWebjars();
					config.enableCorsForAllOrigins();
					config.requestCacheSize = (long) 2000000000;
				});
		        app.start(getHerokuAssignedPort());
	
		        
		            app.get("/", ctx->{
		             ctx.html("<!doctype html>\r\n"
		             		+ "<html lang=\"en\">\r\n"
		             		+ "<head>\r\n"
		             		+ "    <meta charset=\"UTF-8\">\r\n"
		             		+ "    <meta name=\"viewport\"\r\n"
		             		+ "          content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n"
		             		+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n"
		             		+ "    <meta http-equiv=\"Content-Security-Policy\" content=\"upgrade-insecure-requests\">\r\n"
		             		+ "    <title>Weather App</title>\r\n"
		             		+ "    <link type=\"text/css\" rel=\"stylesheet\" href=\"index.css\" >\r\n"
		             		+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n"
		             		+ "    \r\n"
		             		+ "    <style>\r\n"
		             		+ "        /*========= Shared styles ==================*/\r\n"
		             		+ "body{\r\n"
		             		+ "background-color: #08758A;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".app-row{\r\n"
		             		+ "    width: calc(100%-10px);\r\n"
		             		+ "    margin: 5px;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".app-row:after{\r\n"
		             		+ "    width:100%;\r\n"
		             		+ "    height:100%;\r\n"
		             		+ "    content: \"\";\r\n"
		             		+ "    display:table;\r\n"
		             		+ "    clear: both;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".app-col{\r\n"
		             		+ "    float:left;\r\n"
		             		+ "    margin-top: 5px;;\r\n"
		             		+ "    width: 33.33%;\r\n"
		             		+ "    height: 100%;\r\n"
		             		+ "    padding:10px;\r\n"
		             		+ "    color: gray;\r\n"
		             		+ "    background-color: whitesmoke;\r\n"
		             		+ "    text-align: center;\r\n"
		             		+ "    cursor: pointer;\r\n"
		             		+ "    list-style-type: none;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".active-nav{\r\n"
		             		+ " color:firebrick;\r\n"
		             		+ " border-bottom: 5px solid firebrick;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".non-active-nav{\r\n"
		             		+ " color:gray;\r\n"
		             		+ " text-decoration: none;   \r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "\r\n"
		             		+ "#page{\r\n"
		             		+ "width: 100%;\r\n"
		             		+ "height: 100%;\r\n"
		             		+ "position : relative;\r\n"
		             		+ "overflow-y: auto;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "#location{\r\n"
		             		+ "position: absolute;\r\n"
		             		+ "right:0;\r\n"
		             		+ "top:0;\r\n"
		             		+ "left:calc(50%-10px);\r\n"
		             		+ "right:10px;\r\n"
		             		+ "width: 40%;\r\n"
		             		+ "height: 100%;\r\n"
		             		+ "background-color: white;\r\n"
		             		+ "border: 2px solid gray;\r\n"
		             		+ "display: none;\r\n"
		             		+ "overflow-x:hidden;\r\n"
		             		+ "overflow-y:auto;\r\n"
		             		+ "text-align: justify;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".search-label{\r\n"
		             		+ "background-color: #08758A;\r\n"
		             		+ "color:white;\r\n"
		             		+ "font-size: 18px;\r\n"
		             		+ "text-align: center;\r\n"
		             		+ "font-weight: bold;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".cities{\r\n"
		             		+ "font-size: 15px;\r\n"
		             		+ "color: #08758A;\r\n"
		             		+ "padding:5px;\r\n"
		             		+ "width:100%;\r\n"
		             		+ "margin: 0px;\r\n"
		             		+ "text-align: center;\r\n"
		             		+ "border: 1px solid gray;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".div-block-top{\r\n"
		             		+ "background-color: white;\r\n"
		             		+ "margin: 5px;\r\n"
		             		+ "padding: 10px;\r\n"
		             		+ "width: calc(100%-10px);\r\n"
		             		+ "height: 40%;\r\n"
		             		+ "border: 2px solid light-gray;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".div-block-bottom{\r\n"
		             		+ "background-color: white;\r\n"
		             		+ "margin: 5px;\r\n"
		             		+ "padding: 10px;\r\n"
		             		+ "width: calc(100%-10px);\r\n"
		             		+ "height: 60%;\r\n"
		             		+ "border: 2px solid light-gray;\r\n"
		             		+ "overflow-y: auto;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".d_heading .t_heading{\r\n"
		             		+ "margin-top: 20px;\r\n"
		             		+ "font-size:20px;\r\n"
		             		+ "font-weight: bold;\r\n"
		             		+ "text-decoration: black;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "/*=========== Timely Updates =============*/\r\n"
		             		+ ".t_row{\r\n"
		             		+ "width: calc(100%-10px);\r\n"
		             		+ "margin: 5px;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".t_row:after{\r\n"
		             		+ "content: \"\";\r\n"
		             		+ "display: table;\r\n"
		             		+ "clear: both;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".t_col{\r\n"
		             		+ "float: left;\r\n"
		             		+ "width: 25%;\r\n"
		             		+ "text-align: center;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".t_temp{\r\n"
		             		+ "content: \"\\00B0\";\r\n"
		             		+ "margin-top: 10px;\r\n"
		             		+ "font-size:12px;\r\n"
		             		+ "font-weight: bold;\r\n"
		             		+ "text-align: center;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".t_rain{\r\n"
		             		+ "margin-top: 10px;\r\n"
		             		+ "font-size:12px;\r\n"
		             		+ "color: #08758A\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".t_icon{\r\n"
		             		+ "margin-top: 10px;\r\n"
		             		+ "width: 20px;\r\n"
		             		+ "height: 20px;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".t_time{\r\n"
		             		+ "margin-top: 10px;\r\n"
		             		+ "font-size:12px;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "\r\n"
		             		+ "\r\n"
		             		+ "/* ========== Daily Updates ================*/\r\n"
		             		+ ".d_col{\r\n"
		             		+ "width: 100%;\r\n"
		             		+ "max-height: 60%;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".d_row{\r\n"
		             		+ "width: 100%;\r\n"
		             		+ "height: 20%;\r\n"
		             		+ "display: flex;\r\n"
		             		+ "justify-content: center;\r\n"
		             		+ "text-align: center;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".d_span1{\r\n"
		             		+ "width: 25%;\r\n"
		             		+ "float:left;\r\n"
		             		+ "display: flex;\r\n"
		             		+ "justify-content: center;\r\n"
		             		+ "text-align: center;\r\n"
		             		+ "margin-top:20px;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".d_span2{\r\n"
		             		+ "width: 50%;\r\n"
		             		+ "float:left;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".d_span3{\r\n"
		             		+ "width: 25%;\r\n"
		             		+ "float:left;\r\n"
		             		+ "margin-top:20px;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".d_icon{\r\n"
		             		+ "margin-top: 10px;\r\n"
		             		+ "width: 20px;\r\n"
		             		+ "height: 20px;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".d_date{\r\n"
		             		+ "content: \"\\00B0\";\r\n"
		             		+ "margin-top: 20px;\r\n"
		             		+ "font-size:12px;\r\n"
		             		+ "font-weight: bold;\r\n"
		             		+ "text-align: center;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".d_desc{\r\n"
		             		+ "content: \"\\00B0\";\r\n"
		             		+ "margin-top: 20px;\r\n"
		             		+ "font-size:12px;\r\n"
		             		+ "text-align: center;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ ".d_temp{\r\n"
		             		+ "content: \"\\00B0\";\r\n"
		             		+ "margin-top: 20px;\r\n"
		             		+ "font-size:12px;\r\n"
		             		+ "font-weight: bold;\r\n"
		             		+ "text-align: center;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "    </style>\r\n"
		             		+ "    <style>\r\n"
		             		+ "      * {box-sizing: border-box;}\r\n"
		             		+ "      \r\n"
		             		+ "      body {\r\n"
		             		+ "        margin: 0;\r\n"
		             		+ "        font-family: Arial, Helvetica, sans-serif;\r\n"
		             		+ "      }\r\n"
		             		+ "      \r\n"
		             		+ "      .topnav {\r\n"
		             		+ "        height: 60px;\r\n"
		             		+ "        width: 100%;\r\n"
		             		+ "        margin-left: 2px;\r\n"
		             		+ "        margin-right: 2px;\r\n"
		             		+ "        margin-top: 5px;\r\n"
		             		+ "        margin-bottom: 0px;\r\n"
		             		+ "        overflow: hidden;\r\n"
		             		+ "        background-color: #08458A;\r\n"
		             		+ "        color: white;\r\n"
		             		+ "      }\r\n"
		             		+ "      \r\n"
		             		+ "      .topnav a {\r\n"
		             		+ "        float: left;\r\n"
		             		+ "        display: block;\r\n"
		             		+ "        color: white;\r\n"
		             		+ "        text-align: center;\r\n"
		             		+ "        padding: 14px 16px;\r\n"
		             		+ "        text-decoration: none;\r\n"
		             		+ "        font-size: 18px;\r\n"
		             		+ "      }\r\n"
		             		+ "      \r\n"
		             		+ "      .topnav input[type=text] {\r\n"
		             		+ "        padding: 6px;\r\n"
		             		+ "        margin-top: 8px;\r\n"
		             		+ "        font-size: 17px;\r\n"
		             		+ "        border: none;\r\n"
		             		+ "      }\r\n"
		             		+ "      \r\n"
		             		+ "      .topnav .search-container button {\r\n"
		             		+ "        float: right;\r\n"
		             		+ "        padding: 5px;\r\n"
		             		+ "        margin-top: 5px;\r\n"
		             		+ "        margin-right: 2px;\r\n"
		             		+ "        background: #ddd;\r\n"
		             		+ "        font-size: 12px;\r\n"
		             		+ "        border: none;\r\n"
		             		+ "        cursor: pointer;\r\n"
		             		+ "      }\r\n"
		             		+ "      \r\n"
		             		+ "    \r\n"
		             		+ "      .search-box{\r\n"
		             		+ "        float:right;\r\n"
		             		+ "        margin-top: 5px;\r\n"
		             		+ "      }\r\n"
		             		+ "      \r\n"
		             		+ "      @media screen and (max-width: 600px) {\r\n"
		             		+ "        .topnav .search-container .app-col{\r\n"
		             		+ "          float: none;\r\n"
		             		+ "          margin-top: 5px;\r\n"
		             		+ "        }\r\n"
		             		+ "        .topnav a, .topnav input[type=text], .topnav .search-container button {\r\n"
		             		+ "          float: none;\r\n"
		             		+ "          display: block;\r\n"
		             		+ "          text-align: left;\r\n"
		             		+ "          width: 100%;\r\n"
		             		+ "          margin: 0;\r\n"
		             		+ "          padding: 14px;\r\n"
		             		+ "        }\r\n"
		             		+ "        .app-row {\r\n"
		             		+ "          width: 100%;\r\n"
		             		+ "        }\r\n"
		             		+ "\r\n"
		             		+ "        .app-row:after{\r\n"
		             		+ "          content: \"\";\r\n"
		             		+ "          clear: both;\r\n"
		             		+ "          display: table;\r\n"
		             		+ "        }\r\n"
		             		+ "        .app-col {\r\n"
		             		+ "          float: left;\r\n"
		             		+ "          text-align: center;\r\n"
		             		+ "          width: 33.33%;\r\n"
		             		+ "          height: 30px;\r\n"
		             		+ "          margin-left: 0;\r\n"
		             		+ "          margin-right: 0;\r\n"
		             		+ "          margin-top: 5px;\r\n"
		             		+ "          margin-bottom: 5px;\r\n"
		             		+ "          font-size: 12px;\r\n"
		             		+ "          padding: 5px;\r\n"
		             		+ "          overflow: hidden;\r\n"
		             		+ "        }\r\n"
		             		+ "        .active-nav {\r\n"
		             		+ "           color:firebrick;\r\n"
		             		+ "           border-bottom: 5px solid firebrick;\r\n"
		             		+ "        }\r\n"
		             		+ "        .non-active-nav {\r\n"
		             		+ "           color:gray;\r\n"
		             		+ "           text-decoration: none;   \r\n"
		             		+ "        }\r\n"
		             		+ "\r\n"
		             		+ "        \r\n"
		             		+ "        .topnav input[type=text] {\r\n"
		             		+ "          border: 1px solid #ccc;  \r\n"
		             		+ "        }\r\n"
		             		+ "      }\r\n"
		             		+ "      </style>\r\n"
		             		+ "      \r\n"
		             		+ "</head>\r\n"
		             		+ "<body>\r\n"
		             		+ "       <div class=\"topnav\">\r\n"
		             		+ "          <a class=\"active\" href=\"#name\" style=\"width: 100%;\"><span style=\"width: 100%;\"><span style=\"float: left;width: 80%;\"><p style=\"text-align: left;margin-top: 5px;\">Sample Weather</p></span><span style=\"float: right;margin-right: 0px;width: 20%;text-align: right;\"><i class=\"fa fa-search\"  onclick=\"handleHide()\"></i></span></span></a>\r\n"
		             		+ "       </div>\r\n"
		             		+ "\r\n"
		             		+ "    <div class=\"app-row\">\r\n"
		             		+ "        <a class=\"app-col active-nav\" href=\"#\" onclick=\"handle_col1()\"></a>\r\n"
		             		+ "        <a class=\"app-col\" href=\"#\" onclick=\"handle_col2()\"></a>\r\n"
		             		+ "        <a class=\"app-col\" href=\"#\" onclick=\"handle_col3()\"></a>\r\n"
		             		+ "    </div>\r\n"
		             		+ "                      <div id=\"page\"> \r\n"
		             		+ "                          <div class=\"div-block-top\">\r\n"
		             		+ "                             <form action=\"#\">\r\n"
		             		+ "                              <span class=\"search-span\" style=\"display: none;\"> \r\n"
		             		+ "                              <button class=\"search-box\" style=\"background-color: green;color: white;\" onclick=\"handleSearch()\">Go</button>\r\n"
		             		+ "                              <input class=\"search-box\" type=\"text\" placeholder=\"you can also search city...\" id=\"search_value\"/>\r\n"
		             		+ "                              </span>\r\n"
		             		+ "                              </form>\r\n"
		             		+ "                             <p class=\"t_heading\"></p>\r\n"
		             		+ "                            <div class=\"t_row\"><div class=\"t_col\">\r\n"
		             		+ "\r\n"
		             		+ "\r\n"
		             		+ "                     <p class=\"t_temp\"></p>\r\n"
		             		+ "                     <p class=\"t_rain\"></p>\r\n"
		             		+ "                     <img class=\"t_icon\" alt=\"icon\"/>\r\n"
		             		+ "                     <p class=\"t_time\"></p>\r\n"
		             		+ "                   </div>\r\n"
		             		+ "\r\n"
		             		+ "                   <div class=\"t_col\">\r\n"
		             		+ "                     <p class=\"t_temp\"></p>\r\n"
		             		+ "                     <p class=\"t_rain\"></p>\r\n"
		             		+ "                     <img src=\"\" class=\"t_icon\" alt=\"icon\"/>\r\n"
		             		+ "                     <p class=\"t_time\"></p>\r\n"
		             		+ "                   </div>\r\n"
		             		+ "\r\n"
		             		+ "                   <div class=\"t_col\">\r\n"
		             		+ "                    <p class=\"t_temp\"></p>\r\n"
		             		+ "                    <p class=\"t_rain\"></p>\r\n"
		             		+ "                    <img src=\"\" class=\"t_icon\" alt=\"icon\"/>\r\n"
		             		+ "                    <p class=\"t_time\"></p>\r\n"
		             		+ "                   </div>\r\n"
		             		+ "\r\n"
		             		+ "                   <div class=\"t_col\">\r\n"
		             		+ "                    <p class=\"t_temp\"></p>\r\n"
		             		+ "                    <p class=\"t_rain\"></p>\r\n"
		             		+ "                    <img src=\"\" class=\"t_icon\" alt=\"icon\"/>\r\n"
		             		+ "                    <p class=\"t_time\"></p>\r\n"
		             		+ "                  </div>\r\n"
		             		+ "           </div>\r\n"
		             		+ "\r\n"
		             		+ "       \r\n"
		             		+ "\r\n"
		             		+ "       </div>\r\n"
		             		+ "       \r\n"
		             		+ "       \r\n"
		             		+ "       <div class=\"div-block-bottom\">\r\n"
		             		+ "        <p class=\"d_heading\"></p>\r\n"
		             		+ "        <div class=\"d_col\">\r\n"
		             		+ "       \r\n"
		             		+ "          <div class=\"d_row\">\r\n"
		             		+ "          <span class=\"d_span1\">\r\n"
		             		+ "            <img class=\"d_icon\"/>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span2\">\r\n"
		             		+ "             <p class=\"d_date\"></p>\r\n"
		             		+ "             <p class=\"d_desc\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span3\">\r\n"
		             		+ "             <p class=\"d_temp\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "        </div>\r\n"
		             		+ "\r\n"
		             		+ "        <div class=\"d_row\">\r\n"
		             		+ "          <span class=\"d_span1\">\r\n"
		             		+ "            <img class=\"d_icon\"/>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span2\">\r\n"
		             		+ "             <p class=\"d_date\"></p>\r\n"
		             		+ "             <p class=\"d_desc\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span3\">\r\n"
		             		+ "             <p class=\"d_temp\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "        </div>\r\n"
		             		+ "       \r\n"
		             		+ "        <div class=\"d_row\">\r\n"
		             		+ "          <span class=\"d_span1\">\r\n"
		             		+ "            <img class=\"d_icon\"/>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span2\">\r\n"
		             		+ "             <p class=\"d_date\"></p>\r\n"
		             		+ "             <p class=\"d_desc\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span3\">\r\n"
		             		+ "             <p class=\"d_temp\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "        </div>\r\n"
		             		+ "       \r\n"
		             		+ "        <div class=\"d_row\">\r\n"
		             		+ "          <span class=\"d_span1\">\r\n"
		             		+ "            <img class=\"d_icon\"/>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span2\">\r\n"
		             		+ "             <p class=\"d_date\"></p>\r\n"
		             		+ "             <p class=\"d_desc\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span3\">\r\n"
		             		+ "             <p class=\"d_temp\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "        </div>\r\n"
		             		+ "       \r\n"
		             		+ "        <div class=\"d_row\">\r\n"
		             		+ "          <span class=\"d_span1\">\r\n"
		             		+ "            <img class=\"d_icon\"/>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span2\">\r\n"
		             		+ "             <p class=\"d_date\"></p>\r\n"
		             		+ "             <p class=\"d_desc\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "          <span class=\"d_span3\">\r\n"
		             		+ "             <p class=\"d_temp\"></p>\r\n"
		             		+ "          </span>\r\n"
		             		+ "        </div>\r\n"
		             		+ "       \r\n"
		             		+ "\r\n"
		             		+ "       </div>\r\n"
		             		+ "\r\n"
		             		+ "\r\n"
		             		+ "      </div>\r\n"
		             		+ "\r\n"
		             		+ "\r\n"
		             		+ "      <div>\r\n"
		             		+ "        <span><p class=\"created-by\" style=\"font-size: 12px;color: white;text-align: center;\">Powered by Ade Dosunmu &#169 2024</p></span>\r\n"
		             		+ "      </div>\r\n"
		             		+ "\r\n"
		             		+ "<noscript>Please Enable JavaScript for ths page to work properly</noscript>\r\n"
		             		+ "<script src=\"index.js\"></script>\r\n"
		             		+ "<script>\r\n"
		             		+ "  // API Fetch Initial Variables\r\n"
		             		+ "const ria_api_key = \"482944e26d320a80bd5e4f23b3de7d1f\";\r\n"
		             		+ "const my_api_key = \"0f625f5b0482a767f98983091bdac3d4\";\r\n"
		             		+ "const http = \"http://\";\r\n"
		             		+ "function fetchData(city){\r\n"
		             		+ "const forecast_url = `${http}api.openweathermap.org/data/2.5/forecast?q=${city}&appid=${my_api_key}`;\r\n"
		             		+ "// using AbortController to detect anormality during api fetch\r\n"
		             		+ "const controller = new AbortController();\r\n"
		             		+ "const signal = controller.signal;var isOk;\r\n"
		             		+ "const fetchPromise = fetch(forecast_url, { signal }); // api for the get request\r\n"
		             		+ "  // Timeout after 5 seconds\r\n"
		             		+ "const timeoutId = setTimeout(() => {\r\n"
		             		+ "controller.abort(); // Abort the fetch request\r\n"
		             		+ "console.log('Fetch request timed out');\r\n"
		             		+ "}, 5000);  \r\n"
		             		+ "// Handle the fetch request\r\n"
		             		+ "fetchPromise\r\n"
		             		+ ".then(response => {\r\n"
		             		+ "  // Check if the request was successful\r\n"
		             		+ "  if (!response.ok) { isOk=0;\r\n"
		             		+ "  throw new Error('Network response was not ok');\r\n"
		             		+ "  } \r\n"
		             		+ "  // Parse the response as JSON\r\n"
		             		+ "  document.getElementsByClassName('t_heading')[0].innerText = \"Next Hours\";\r\n"
		             		+ "  document.getElementsByClassName('d_heading')[0].innerText = \"Next 5 days\";\r\n"
		             		+ "  return response.json();\r\n"
		             		+ "})  // data munging and wrangling begins\r\n"
		             		+ ".then(data => {isOk=JSON.stringify(data.list.length);\r\n"
		             		+ "  try{\r\n"
		             		+ "    for (i=0; i<4; i++){ \r\n"
		             		+ "      document.getElementsByClassName(\"t_temp\")[i].innerText=parseInt(JSON.parse(JSON.stringify(data.list[i])).main.temp)-273+String.fromCharCode(176);\r\n"
		             		+ "      document.getElementsByClassName(\"t_rain\")[i].innerText=parseInt(JSON.parse(JSON.stringify(data.list[i])).pop)+String.fromCharCode(37);\r\n"
		             		+ "      document.getElementsByClassName(\"t_icon\")[i].src=get_icon(JSON.parse(JSON.stringify(data.list[i])).weather[0].icon);\r\n"
		             		+ "      document.getElementsByClassName(\"t_time\")[i].innerText=getTm(JSON.parse(JSON.stringify(data.list[i])));\r\n"
		             		+ "      }var k=0;\r\n"
		             		+ "    for (j=0; j<5; j++){\r\n"
		             		+ "      document.getElementsByClassName(\"d_icon\")[j].src=get_icon(JSON.parse(JSON.stringify(data.list[k])).weather[0].icon);\r\n"
		             		+ "      document.getElementsByClassName(\"d_date\")[j].innerText=getDt(JSON.parse(JSON.stringify(data.list[k])));  \r\n"
		             		+ "      document.getElementsByClassName(\"d_desc\")[j].innerText=JSON.parse(JSON.stringify(data.list[k])).weather[0].description;  \r\n"
		             		+ "      document.getElementsByClassName(\"d_temp\")[j].innerText=(parseInt(JSON.parse(JSON.stringify(data.list[k])).main.temp_max)-273)+String.fromCharCode(176)+\" \"+(parseInt(JSON.parse(JSON.stringify(data.list[k])).main.temp_min)-273)+String.fromCharCode(176); \r\n"
		             		+ "      k=k+8;}\r\n"
		             		+ "    } catch (error) {\r\n"
		             		+ "      return;\r\n"
		             		+ "    }\r\n"
		             		+ "    })\r\n"
		             		+ ".catch(error => {\r\n"
		             		+ "    // Handle any errors that occurred during the fetch\r\n"
		             		+ "    console.error('Fetch error:', error);\r\n"
		             		+ "  })\r\n"
		             		+ ".finally(() => {\r\n"
		             		+ "    clearTimeout(timeoutId);return isOk; // Clear the timeout\r\n"
		             		+ "  }); \r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "const daysOfWeek = [\"Sun\", \"Mon\", \"Tue\", \"Wed\", \"Thur\", \"Fri\", \"Sat\"]\r\n"
		             		+ "const month = [\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\", \"Jul\", \"Aug\", \"Sep\", \"Oct\", \"Nov\", \"Dec\"];\r\n"
		             		+ "const get_full_month = [\"January\", \"Febuary\", \"March\", \"April\", \"May\", \"June\", \"July\", \"August\", \"September\", \"October\", \"November\", \"December\"];\r\n"
		             		+ "const get_icon = (icon) => { return `http://openweathermap.org/img/w/${icon}.png`; }; // get icon url\r\n"
		             		+ "\r\n"
		             		+ "//format the time\r\n"
		             		+ "const format_time = (time) => {\r\n"
		             		+ "var ff = parseInt(time.substring(1, 3)); \r\n"
		             		+ "if (ff>12) { ff = ff-12; \r\n"
		             		+ "  return ff.toString()+time.substring(3, 6)+'PM';\r\n"
		             		+ "} else if (ff<12 && ff>0) {ff = ff;\r\n"
		             		+ "  return time.substring(1, 6)+'AM';\r\n"
		             		+ "} else if (ff===12) {\r\n"
		             		+ "  return \"12\"+time.substring(3, 6)+'PM';\r\n"
		             		+ "} else if (ff===24||ff===0) {\r\n"
		             		+ "  return \"12\"+time.substring(3, 6)+'AM';\r\n"
		             		+ "} else {\r\n"
		             		+ "  return time.substring(1, 6)+'AM';\r\n"
		             		+ "}\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "// get date in string\r\n"
		             		+ "const getParsedDateString = (month_int, day_int, year_int) => {\r\n"
		             		+ "year_int = parseInt(year_int); month_int = parseInt(month_int)-1;day_int = parseInt(day_int);\r\n"
		             		+ "const full_month = get_full_month[month_int];\r\n"
		             		+ "const parsedDateToString = `${full_month} ${day_int.toString()}, ${year_int.toString()}`;\r\n"
		             		+ "return parsedDateToString;\r\n"
		             		+ "} \r\n"
		             		+ "\r\n"
		             		+ "// get short date\r\n"
		             		+ "const getDt = (d1o) =>{\r\n"
		             		+ "      const time_string = d1o.dt_txt.substring(d1o.dt_txt.length-9,d1o.dt_txt.length);\r\n"
		             		+ "      const date_string = d1o.dt_txt.substring(0,10);const day_string = date_string.substring(8,10);\r\n"
		             		+ "      const month_string = date_string.substring(5,7);const year_string = date_string.substring(0,4);\r\n"
		             		+ "      const date_txt = getParsedDateString(month_string, day_string, year_string);//console.log(\"parsed_date_txt: \"+date_txt) \r\n"
		             		+ "      const day_dt = new Date(d1o.dt); //console.log(\"date_from_dt: \"+day_dt);\r\n"
		             		+ "      const day_txt = new Date(Date.parse(date_txt)); //console.log(\"date_from_txt: \"+day_txt);\r\n"
		             		+ "      const dateFromDT = `${daysOfWeek[day_dt.getDay()]}, ${month[day_dt.getMonth()]} ${day_dt.getDate()}`; //console.log(\"short_date_from_dt: \"+dateFromDT);\r\n"
		             		+ "      const dateFromTXT = `${daysOfWeek[day_txt.getDay()]}, ${month[day_txt.getMonth()]} ${day_txt.getDate()}`; //console.log(\"short_date_from_txt: \"+dateFromTXT);\r\n"
		             		+ "      const date = dateFromTXT; //console.log(\"actual_short_Date: \"+date);\r\n"
		             		+ "      return dateFromTXT;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "// get time\r\n"
		             		+ "const getTm = (d1o) => {\r\n"
		             		+ "      const time_string = d1o.dt_txt.substring(d1o.dt_txt.length-9,d1o.dt_txt.length);\r\n"
		             		+ "      const tt = format_time(time_string);\r\n"
		             		+ "      return tt;\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "const handleHide = () => {\r\n"
		             		+ "const search_span = document.getElementsByClassName('search-span')[0];\r\n"
		             		+ "if (search_span.style.display==='none'){\r\n"
		             		+ "search_span.style.display='block';\r\n"
		             		+ "} else {\r\n"
		             		+ "search_span.style.display='none';\r\n"
		             		+ "}\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "\r\n"
		             		+ "\r\n"
		             		+ "</script>\r\n"
		             		+ "\r\n"
		             		+ "<script>\r\n"
		             		+ "const _cities = new Array(\"LOS ANGELES\", \"BEIJING\", \"RIO DE JANEIRO\");\r\n"
		             		+ "var last_col1=_cities[2];var last_col2=_cities[1]; var last_col3=_cities[0];\r\n"
		             		+ "var col1_actv=true;var col2_actv=false; var col3_act=false;\r\n"
		             		+ "\r\n"
		             		+ "const load3 = () => {\r\n"
		             		+ "    document.getElementsByClassName('app-col')[2].innerHTML=_cities[0];\r\n"
		             		+ "  }\r\n"
		             		+ "load3();\r\n"
		             		+ "\r\n"
		             		+ "const load2 = () => {\r\n"
		             		+ "    document.getElementsByClassName('app-col')[1].innerHTML=_cities[1];\r\n"
		             		+ "  }\r\n"
		             		+ "load2();\r\n"
		             		+ "\r\n"
		             		+ "const load1 = () => {\r\n"
		             		+ "    document.getElementsByClassName('app-col')[0].innerHTML=_cities[2];\r\n"
		             		+ "    fetchData(_cities[2]); last_col1=_cities[2];\r\n"
		             		+ "    col1_actv=true;col2_actv=false;col3_act=false;\r\n"
		             		+ "  }\r\n"
		             		+ "load1();\r\n"
		             		+ "\r\n"
		             		+ "const handle_col1 = () => {\r\n"
		             		+ "  fetchData(last_col1);\r\n"
		             		+ "  document.getElementsByClassName('app-col')[0].innerHTML=last_col1.toUpperCase();;\r\n"
		             		+ "  last_col1=last_col1;col1_actv=true;col2_actv=false;col3_act=false;\r\n"
		             		+ "  change_pointer();handleHide();\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "const handle_col2 = () => {\r\n"
		             		+ "  fetchData(last_col2);\r\n"
		             		+ "  document.getElementsByClassName('app-col')[1].innerHTML=last_col2.toUpperCase();;\r\n"
		             		+ "  last_col2=last_col2;col2_actv=true;col1_actv=false;col3_act=false;\r\n"
		             		+ "  change_pointer();handleHide();\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "const handle_col3 = () => {\r\n"
		             		+ "  fetchData(last_col3);\r\n"
		             		+ "  document.getElementsByClassName('app-col')[2].innerHTML=last_col3.toUpperCase();;\r\n"
		             		+ "  last_col3=last_col3;col3_actv=true;col1_actv=false;col2_act=false;\r\n"
		             		+ "  change_pointer();handleHide();\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ " // handle search \r\n"
		             		+ "  handleSearch = () => {\r\n"
		             		+ "  search = document.getElementById('search_value').value;\r\n"
		             		+ "  console.log(search);\r\n"
		             		+ "  console.log(\"isITOkay?: \"+fetchData(search));\r\n"
		             		+ "  if(search!==\"\")\r\n"
		             		+ "  document.getElementsByClassName('app-col')[0].innerText=search.toUpperCase();\r\n"
		             		+ "  document.getElementById('search_value').value=\"\";\r\n"
		             		+ "  col1_actv=true;col2_actv=false;col3_act=false;last_col1=search;\r\n"
		             		+ "  change_pointer();handleHide();}\r\n"
		             		+ "\r\n"
		             		+ "const change_pointer = () => {\r\n"
		             		+ "  if(col1_actv){\r\n"
		             		+ "    document.getElementsByClassName('app-col')[0].style.borderBottom = \"5px solid firebrick\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[0].style.color = \"firebrick\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[1].style.borderBottom = \"none\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[1].style.color = \"gray\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[2].style.borderBottom = \"none\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[2].style.color = \"gray\";\r\n"
		             		+ "    if (document.getElementsByClassName('app-col')[0].innerText===\"\")load1();\r\n"
		             		+ "  }\r\n"
		             		+ "  else if(col2_actv){\r\n"
		             		+ "    document.getElementsByClassName('app-col')[1].style.borderBottom = \"5px solid firebrick\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[1].style.color = \"firebrick\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[0].style.borderBottom = \"none\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[0].style.color = \"gray\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[2].style.borderBottom = \"none\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[2].style.color = \"gray\";\r\n"
		             		+ "    if (document.getElementsByClassName('app-col')[1].innerText===\"\")load2();\r\n"
		             		+ "  } \r\n"
		             		+ "  else if(col3_actv){\r\n"
		             		+ "    document.getElementsByClassName('app-col')[2].style.borderBottom = \"5px solid firebrick\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[2].style.color = \"firebrick\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[1].style.borderBottom = \"none\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[1].style.color = \"gray\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[0].style.borderBottom = \"none\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[0].style.color = \"gray\";\r\n"
		             		+ "    if (document.getElementsByClassName('app-col')[2].innerText===\"\")load3();  \r\n"
		             		+ "  } else {\r\n"
		             		+ "    document.getElementsByClassName('app-col')[0].style.borderBottom = \"5px solid firebrick\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[0].style.color = \"firebrick\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[1].style.borderBottom = \"none\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[1].style.color = \"gray\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[2].style.borderBottom = \"none\";\r\n"
		             		+ "    document.getElementsByClassName('app-col')[2].style.color = \"gray\";\r\n"
		             		+ "    handle_col1();\r\n"
		             		+ "   }\r\n"
		             		+ "}\r\n"
		             		+ "\r\n"
		             		+ "</script>\r\n"
		             		+ "\r\n"
		             		+ "\r\n"
		             		+ "</body>\r\n"
		             		+ "</html>\r\n"
		             		+ "\r\n"
		             		+ "");
		   		 }); 
          
	
		            
		            
		            
	}
	
	//heroku port assignment
		private static int getHerokuAssignedPort() {
	        String herokuPort = System.getenv("PORT");
	        if (herokuPort != null) {
	          return Integer.parseInt(herokuPort);
	        }
	        return 7000;
	      }
			
		
		
}

